development:
  sessions:
    default:
      database: anode_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: anode_test
      hosts:
        - localhost:27017

# set these environment variables on your prod server
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true
