development:
  host: localhost
  database: anode_development

test:
  host: localhost
  database: anode_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
